### ISSUE TITLE
Trying to use Overlay. RP not found

### ISSUE THREAD

**Issue by echnaton999** [mafredri/cdp#20] opened 2017-07-30 16:49 UTC
Hi everybody,

I'm trying to show a rectangle in a chromium browser.

`color := cdptype.DOMRGBA{R: 255, G: 0, B: 0} `
`cerr := c.Overlay.HighlightRect(ctx, cdpcmd.NewOverlayHighlightRectArgs(5, 5, 20, 20).SetColor(color))`
`if cerr != nil {`
`	panic(cerr)`
`}`

I get following error:
`'Overlay.highlightRect' wasn't found (code = -32601)`

There seems to be a mismatch between domains (There is a Highlight in the DOM Domain?)

Thank you! Keep up the great work!

**Comment by mafredri** [comment] 2017-08-04 11:17
Hi @echnaton999, sorry for the slow response time, I've been away on vacation and just got back yesterday!

Which version of Chrome are you using? I can't reproduce the error using any of Chrome Stable (60.0.3112.90), Chrome Beta (60.0.3112.78) or Chrome Canary (62.0.3176.0).

Currently `cdp` is generated from the latest tip-of-tree (tot) protocol definition, so it can conflict with older versions. I'm actively thinking of ways to use different protocol versions though.

> There seems to be a mismatch between domains (There is a Highlight in the DOM Domain?)

Ah, thanks for bringing this up. The ones in the DOM domain shouldn't be used as they have been moved to the Overlay domain.

They are defined as follows (DOM):

```json
{
  "name": "highlightRect",
  "description": "Highlights given rectangle.",
  "redirect": "Overlay"
},
{
  "name": "highlightNode",
  "description": "Highlights DOM node.",
  "redirect": "Overlay"
},
{
  "name": "hideHighlight",
  "description": "Hides any highlight.",
  "redirect": "Overlay"
}
```

This needs to be handled better when generating the protocol. I'll try to improve this ASAP 😄!

---

**PS.** I noticed you're using `cdptype` and `cdpcmd` above, are you using `v0.8.0`? I highly recommend updating, from `v0.9.0` the above would look like this:

```go
color := dom.RGBA{R: 255, G: 0, B: 0}
cerr := c.Overlay.HighlightRect(ctx, overlay.NewHighlightRectArgs(5, 5, 20, 20).SetColor(color))
if cerr != nil {
	panic(cerr)
}
```

**Comment by matthewmueller** [comment] 2017-08-04 17:06
@echnaton999 i think i ran into that too. i think the solution i had to update chrome to get rectangles to show up.

also i think you need to call Overlay.enable if you haven't already

**Comment by mafredri** [comment] 2017-08-05 00:50
I just pushed https://github.com/mafredri/cdp/commit/de519ff858b7c1f025f64f466341daaeb35cdfda which removes all the redirected commands. This should help to avoid confusion between which one to use.

Since the official [protocol viewer](https://chromedevtools.github.io/devtools-protocol/tot/) doesn't show redirected commands, I decided to go the same route here.

I'm considering providing these redirections in code as well, but I haven't settled on it. Ultimately it might increase the maintenance burden for this lib and might not reduce it for the user either.

**Comment by mafredri** [comment] 2017-08-05 17:15
@echnaton999 by the way, while not ideal, it's possible to work around some protocol mismatches (due to variations in chrome versions) by issuing the command manually via `rpcc`. Here's how you could execute the same method from the DOM-domain.

```go
color := dom.RGBA{R: 255, G: 0, B: 0}
highlightArgs := overlay.NewHighlightRectArgs(5, 5, 20, 20).SetColor(color)
err := rpcc.Invoke(ctx, "DOM.highlightRect", highlightArgs, nil, conn)
```

**Comment by echnaton999** [comment] 2017-08-10 09:30
@mafredri thank you very much for the hints! Now it works though the rectangle shows up for only a fraction of a second. But this is something related to chrome protocol probably.
What I did:
1. Use Chrome Canary in the latest version
2. Upgrade cdp to the latest version by cloning again
3. Call `Overlay.enable`. Thanks @matthewmueller !

Questions which arised during implementation:
1. Is there a way finding out which version of cdp I'm using?
2. Is there any documentation of the protocol besides https://chromedevtools.github.io/devtools-protocol/tot, which is very sparse?
3. Is there a way connecting to a domain and showing all Events/Messages?

Thanks and have a great day!

**Comment by mafredri** [comment] 2017-08-10 19:39
@echnaton999 I'm glad you made some progress!

> 1. Is there a way finding out which version of cdp I'm using?

Are you using anything for managing your dependencies, e.g. `dep`? I will be more actively tagging releases from now on and you can find them on the [releases](https://github.com/mafredri/cdp/releases) page. Generally I try to follow semver as close as possible (not at 1.0.0 yet though) but breaking changes in the protocol are out of my hands and might not warrant a bump in the major version, I'll evaluate on a case-by-case basis.

> 2. Is there any documentation of the protocol besides https://chromedevtools.github.io/devtools-protocol/tot, which is very sparse?

Unfortunately, not much (at least officially). Bits and pieces are scattered across GitHub repos, mailing lists, etc. There is this projects [API documentation (GoDoc)](https://godoc.org/github.com/mafredri/cdp) which contains much of the same information as the DevTools Protocol Viewer, in a different format. Other than that I recommend checking the [Resources](https://github.com/mafredri/cdp#resources) section in the readme and both the issue tracker and wiki of `chrome-remote-interface` can provide some hints as to how the protocol works and behaves.

> 3. Is there a way connecting to a domain and showing all Events/Messages?

Not right now, at least. But I'm actively thinking of ways to improve this situation. Is this something you want to do because the documentation is lacking or because you don't *trust* that the browsers internal protocol matches `cdp`? For the latter I have some ideas (see below).

In the few last versions of Chrome, they have included the http://localhost:9222/json/protocol endpoint which shows the full protocol of the Chrome version you're working against. You can use this to manually check the contents of each domain.

In future I would like for `cdp` to be able to:

- Validate the browsers protocol against `cdp`
- Return error when a method is called that does not exist in the browsers protocol
- Redirect `cdp` methods on-the-fly if the protocols differ (e.g. you call `c.Overlay.HighlightRect` but under the hood this is redirected to `DOM.highlightRect`)
- Manually resolving redirects if they can't be done automatically, e.g. `Validate` reports that `X` is invalid, so you provide the mapping `X -> Y`

> Thanks and have a great day!

Thanks, and to you as well 😄!

**Comment by mafredri** [comment] 2017-09-03 20:17
@echnaton999 I hope I've managed to provide proper answers for you. I'm closing this now but feel free to re-open, or open new issues if you still have any open questions!

**Closed by mafredri** 2017-09-03 20:17 UTC
